[project]
name = 'Digital-Art-Rights-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.art-nft]
path = 'contracts/art-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.artwork-registration]
path = 'contracts/artwork-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
